# @package _global_

defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

  - timelag: defaults
  - duration: defaults
  - acoustic: defaults

verbose: 100

# Synthesis I/O file paths
label_path:
out_wav_path:

# Setting for output WAV file.
bit_depth: 32f
sample_rate: 96000

# How was the model trained.
frame_period: 5
question_path: path/to/qst.hed
log_f0_conditioning: true

# Use ground truth duration or not
# if true, time-lag and duration models will not be used.
ground_truth_duration: false

gain_normalize: false

# If not empty, try to search statisics in the directory
stats_dir:
# If not empty, try to search models in the directory
model_dir:
model_checkpoint: best_loss.pth
